<!DOCTYPE html>
<html lang="en" xmlns:th="http://www.w3.org/1999/xhtml" xmlns:form="http://www.w3.org/1999/html">
<head>
    <link href="style/bootstrap.min.css"
          rel="stylesheet">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, text/html, charset=UTF-8">
    <title>Помилка!</title>
</head>
<body>
<h2>
    ${pageErrors}
</h2>
<h2>
    <a class="btn btn-sm btn-warning" role="button" href="/librarian/participants">Повернутися назад до користувачів</a>
</h2>
</body>
</html>